version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    commit-message:
      prefix: 'chore(deps): update actions'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'npm'
    directory: '/'

    commit-message:
      prefix: 'chore(deps): update dependency version'
    schedule:
      interval: 'daily'
    versioning-strategy: 'increase'
