version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    commit-message:
      prefix: 'chore(deps): update actions'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'npm'
    directory: '/'
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
        
    commit-message:
      prefix: 'chore(deps): update dependency version'
    schedule:
      interval: 'daily'
    versioning-strategy: 'increase'
